version: '3.7'

services:
    web:
        build: ./services/app
        command: gunicorn --bind 0.0.0.0:5000 manage:app
        volumes:
            - ./services/app/:/usr/src/app/
            - static_volume:/usr/src/app/puchineko/static

        expose:
            - 5000
        env_file:
            - ./.env.dev

    nginx:
        build: ./services/nginx
        ports:
            - 1337:80
        depends_on: 
            - web
        volumes:
            - static_volume:/usr/src/app/puchineko/static

volumes:
    static_volume: