version: "2"
services:
  uwsgi:
    build: ./app
    volumes:
            - ./app:/var/www/
    ports:
            - "8080:8080"
              #    networks:
              #            app_net:
              #                    ipv4_address: 172.30.0.3
    environment:
            TZ: "Asia/Tokyo"
                                                                                
  nginx:
    build: ./nginx
    volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
            - uwsgi
    ports:
            - "192.168.33.11:8082:8080"
              #    networks:
              #            app_net:
              #                    ipv4_adress: 172.30.0.2
    environment:
            TZ: "Asia/Tokyo"
  

